[project]
name = "rag-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "faiss-cpu>=1.12.0",
    "inflect>=7.5.0",
    "langchain>=0.3.27",
    "langchain-community>=0.3.29",
    "langchain-ollama>=0.3.8",
    "langchain-unstructured>=0.1.6",
    "ppycron>=1.1.0",
    "python-telegram-bot>=22.4",
    "unstructured>=0.18.15",
]
